development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: db/testpostgresql
  username: systryonka
  password: <%= ENV['DB_DEV_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: db/testpostgresql
  username: systryonka
  # password:

production:
  url: <%= ENV['DATABASE_URL'] %>
